# Generated by Django 6.0.4 on 2026-07-11 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0012_fix_stocknotification_index_name_length"),
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Shopping"),
                            ("facebook", "Facebook Dynamic Product Ads"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Provider must be explicitly enabled before feed targets are generated.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All products"),
                            ("collections", "Selected collections"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only meaningful when scope='collections'. Empty = no products (misconfigured).",
                        related_name="feed_configs",
                        to="catalog.collection",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "feed config",
                "verbose_name_plural": "feed configs",
                "unique_together": {("store", "provider")},
            },
        ),
        migrations.CreateModel(
            name="FeedTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Shopping"),
                            ("facebook", "Facebook Dynamic Product Ads"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2, uppercase — mirrors the parent ShippingCountry row.",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (never generated)"),
                            ("regenerating", "Regenerating"),
                            ("up_to_date", "Up to date"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "is_dirty",
                    models.BooleanField(
                        default=True,
                        help_text="Set by signals on any dependency change; cleared at the start of each regeneration.",
                    ),
                ),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("excluded_count", models.PositiveIntegerField(default=0)),
                (
                    "exclusions_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"reason": "no_image", "product_id": 1, "variant_id": null}, ...] (AC-211).',
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Absolute path under MEDIA_ROOT/feeds/. Empty until the first successful generation.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "store_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_targets",
                        to="stores.storelanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "feed target",
                "verbose_name_plural": "feed targets",
                "indexes": [
                    models.Index(
                        fields=["store", "is_dirty"],
                        name="feeds_feedt_store_i_340f41_idx",
                    )
                ],
                "unique_together": {
                    ("store", "provider", "store_language", "country_code")
                },
            },
        ),
        migrations.CreateModel(
            name="StoreFeedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="secrets.token_urlsafe(32) — never logged, never displayed except in admin's own copy-URL UI.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("rotated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "store feed token",
                "verbose_name_plural": "store feed tokens",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store",), name="unique_feed_token_per_store"
                    )
                ],
            },
        ),
    ]
