# Generated by Django 6.0.4 on 2026-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedtarget",
            name="file_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Absolute path under FEEDS_ROOT (never web-served — security audit F3). Empty until the first successful generation.",
                max_length=500,
            ),
        ),
    ]
