# Generated by Django 6.0.4 on 2026-07-03 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permalink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        help_text="Full URL path without leading slash — e.g. 'products/my-shirt'.",
                        max_length=500,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("collection", "Collection"),
                            ("blog_post", "Blog post"),
                            ("custom", "Custom page"),
                            ("home", "Home"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="PK of the target object. Null for HOME.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "permalink",
                "verbose_name_plural": "permalinks",
                "indexes": [
                    models.Index(
                        fields=["store", "is_active"], name="permalink_store_active_idx"
                    )
                ],
                "unique_together": {("store", "slug")},
            },
        ),
        migrations.CreateModel(
            name="SlugRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Former URL path that should redirect. Without leading slash.",
                        max_length=500,
                    ),
                ),
                (
                    "new_slug",
                    models.CharField(
                        help_text="Current URL path to redirect to. Without leading slash.",
                        max_length=500,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("collection", "Collection"),
                            ("blog_post", "Blog post"),
                            ("custom", "Custom page"),
                            ("home", "Home"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="PK of the target object at the time of redirect creation.",
                        null=True,
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        default=301, help_text="301 (permanent) or 302 (temporary)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "slug redirect",
                "verbose_name_plural": "slug redirects",
                "unique_together": {("store", "old_slug")},
            },
        ),
    ]
