# Generated by Django 6.0.4 on 2026-07-06 07:54

import permalinks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permalinks", "0004_fix_product_permalink_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permalink",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="Full URL path without leading slash — e.g. 'my-shirt' (product) or 'collections/my-collection'.",
                max_length=500,
                validators=[permalinks.models._validate_slug_not_reserved],
            ),
        ),
    ]
