# Generated by Django 6.0.4 on 2026-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permalinks", "0005_alter_permalink_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slugredirect",
            name="trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slug_change", "Slug change"),
                    ("domain_park", "Domain park"),
                    ("import", "Import"),
                    ("page_version_change", "Page version change"),
                ],
                help_text="What caused this redirect to be created.",
                max_length=32,
                null=True,
            ),
        ),
    ]
