# Generated by Django 6.0.4 on 2026-07-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_gift_card"),
        ("discounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Coupon applied to this cart. Re-validated atomically at checkout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="discounts.discountcode",
            ),
        ),
    ]
