# Generated by Django 6.0.4 on 2026-07-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_backfill_converted_cart_session_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="page_version_id",
            field=models.IntegerField(
                blank=True,
                help_text="Soft ID of the ProductPageVersion this line was added from (NULL = primary page). Not an FK — survives version deletion (ADR-028 §1).",
                null=True,
            ),
        ),
    ]
