#ifndef IPAGEREPOSITORY_H
#define IPAGEREPOSITORY_H

#include "website/pages/PageRecord.h"

#include <QHash>
#include <QList>
#include <QString>
#include <optional>

/**
 * CRUD interface for page storage.
 *
 * Page content is stored as a flat key→value map whose structure depends on
 * the page type (see AbstractPageType::save / AbstractPageType::load).
 *
 * Permalink changes are automatically recorded in permalink_history so that
 * redirect rules can be generated by PageGenerator.
 */
class IPageRepository
{
public:
    virtual ~IPageRepository() = default;

    /**
     * Inserts a new page row and returns its assigned id.
     * The page has no bloc data yet; call saveData() after create().
     */
    virtual int create(const QString &typeId,
                       const QString &permalink,
                       const QString &lang) = 0;

    /** Returns the page record for id, or std::nullopt if not found. */
    virtual std::optional<PageRecord> findById(int id) const = 0;

    /** Returns all page records ordered by id ascending. */
    virtual QList<PageRecord> findAll() const = 0;

    /**
     * Replaces all bloc data for the given page with data.
     * Also updates the updated_at timestamp.
     * No-op if id does not exist.
     */
    virtual void saveData(int id, const QHash<QString, QString> &data) = 0;

    /**
     * Loads all bloc data for the given page.
     * Returns an empty hash if id does not exist.
     */
    virtual QHash<QString, QString> loadData(int id) const = 0;

    /**
     * Deletes the page and all its associated data and permalink history.
     * No-op if id does not exist.
     */
    virtual void remove(int id) = 0;

    /**
     * Updates the page's permalink and records the old value in
     * permalink_history with the current UTC timestamp.
     * No-op if id does not exist or the permalink is unchanged.
     */
    virtual void updatePermalink(int id, const QString &newPermalink) = 0;

    /**
     * Returns the permalink history for the given page in chronological order
     * (oldest first).  Each entry is the old permalink that was replaced.
     */
    virtual QList<QString> permalinkHistory(int id) const = 0;
};

#endif // IPAGEREPOSITORY_H
