# Generated by Django 6.0.4 on 2026-07-03 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0003_alter_field_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("product_description", "Product Description"),
                            ("product_seo_title", "Product SEO Title"),
                            ("product_seo_description", "Product SEO Description"),
                            ("collection_description", "Collection Description"),
                            ("image_alt_text", "Image Alt Text"),
                            ("review_response", "Review Response"),
                            ("translation", "Translation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Django app_label.ModelName of the target object, e.g. 'catalog.Product'.",
                        max_length=100,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        help_text="PK of the target object in target_model."
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Target language for translation jobs (ISO 639-1). Empty for non-translation jobs.",
                        max_length=10,
                    ),
                ),
                (
                    "input_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Job input data (source text, context, instructions, etc.).",
                    ),
                ),
                (
                    "requires_human_review",
                    models.BooleanField(
                        default=False,
                        help_text="If True, a validated-DONE job enters the review queue before output is persisted. Translations default False; reviews/promos default True.",
                    ),
                ),
                (
                    "review_verdict",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Set by human reviewer: accept, reject, or request_revision.",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Higher value = higher priority. Translations run at highest priority.",
                    ),
                ),
                ("max_retries", models.PositiveSmallIntegerField(default=3)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "chunk_index",
                    models.IntegerField(
                        default=0,
                        help_text="Index of this chunk when a large input is split proactively (ADR-003 §5).",
                    ),
                ),
                (
                    "total_chunks",
                    models.IntegerField(
                        default=1,
                        help_text="Total number of chunks for this job. 1 means no chunking.",
                    ),
                ),
                (
                    "last_chunk_received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last received chunk (multi-chunk jobs only).",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source that initiated this job: 'rule', 'trigger', or 'human'.",
                        max_length=100,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, do not process before this datetime (deferred jobs).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job",
                "verbose_name_plural": "AI jobs",
            },
        ),
        migrations.CreateModel(
            name="AiJobDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downstream_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_deps",
                        to="aijobs.aijob",
                    ),
                ),
                (
                    "upstream_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_deps",
                        to="aijobs.aijob",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job dependency",
                "verbose_name_plural": "AI job dependencies",
            },
        ),
        migrations.CreateModel(
            name="AiJobMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        help_text="The date (YYYY-MM-DD) this metric row covers."
                    ),
                ),
                (
                    "store_id",
                    models.IntegerField(
                        help_text="Soft reference to the store (no FK — metrics survive store deletion)."
                    ),
                ),
                ("job_type", models.CharField(max_length=100)),
                ("model_id", models.CharField(max_length=100)),
                ("run_count", models.IntegerField(default=0)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "AI job metric",
                "verbose_name_plural": "AI job metrics",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period_date", "store_id", "job_type", "model_id"),
                        name="unique_aijobmetric_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "runner",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Runner type: claude_code, codex, gemini_terminal, or api (fallback).",
                        max_length=50,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Specific model used, e.g. 'claude-sonnet-4-5'.",
                        max_length=100,
                    ),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Updated by the runner every N seconds. Scheduler reclaims runs dead > 3x heartbeat interval (ADR-003 §3).",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="aijobs.aijob",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job run",
                "verbose_name_plural": "AI job runs",
            },
        ),
        migrations.CreateModel(
            name="AiJobOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Raw AI response (all fields). Persisted only after validation passes.",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        help_text="True=applied, False=rejected, None=pending human review.",
                        null=True,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="aijobs.aijob",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="aijobs.aijobrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job output",
                "verbose_name_plural": "AI job outputs",
            },
        ),
        migrations.CreateModel(
            name="AiJobValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("edited", "Edited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("edited_value", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="aijobs.aijoboutput",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job validation",
                "verbose_name_plural": "AI job validations",
            },
        ),
        migrations.CreateModel(
            name="StoreAiQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_budget_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum USD spend per calendar month. 0 with enforced=False means unlimited.",
                        max_digits=10,
                    ),
                ),
                (
                    "current_month_spent_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Running USD total for the current calendar month.",
                        max_digits=10,
                    ),
                ),
                (
                    "current_month",
                    models.DateField(
                        help_text="The first day of the month this counter applies to (YYYY-MM-01)."
                    ),
                ),
                (
                    "is_budget_enforced",
                    models.BooleanField(
                        default=True,
                        help_text="If False, jobs run regardless of monthly_budget_usd. Spending is still tracked for reporting.",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "store AI quota",
                "verbose_name_plural": "store AI quotas",
            },
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["store", "status", "priority"],
                name="aijob_store_status_priority_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aijobdependency",
            constraint=models.UniqueConstraint(
                fields=("upstream_job", "downstream_job"),
                name="unique_aijob_dependency",
            ),
        ),
        migrations.AddConstraint(
            model_name="storeaiquota",
            constraint=models.UniqueConstraint(
                fields=("store",), name="unique_store_ai_quota"
            ),
        ),
    ]
