# Generated by Django 6.0.4 on 2026-07-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aijobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aijob",
            new_name="aijob_store_status_pri_idx",
            old_name="aijob_store_status_priority_idx",
        ),
    ]
