# Generated by Django 6.0.4 on 2026-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aijobs", "0003_output_validation_schema_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="job_type",
            field=models.CharField(max_length=50),
        ),
    ]
