#ifndef LAUNCHERIMPROVE_H
#define LAUNCHERIMPROVE_H

#include "launcher/AbstractLauncher.h"

/**
 * Re-generates underperforming pages using the next-priority strategy.
 *
 * Selection criteria
 * ------------------
 * A page is a candidate when ALL of the following hold:
 *   1. generated_at IS NOT NULL — it was already generated by LauncherGeneration.
 *   2. Its performance is below the configured threshold (--max-impressions, default 0).
 *   3. There exists at least one strategy for its page type that has not yet been
 *      recorded in strategy_attempts for that page.
 *
 * For each candidate, the launcher picks the lowest-numbered untried priority
 * strategy (e.g. priority 2 if priority 1 was already tried), re-generates
 * the page with that strategy's customInstructions plus a failure-context
 * paragraph, and records the new strategy attempt on success.
 *
 * CLI options (in addition to --improve flag):
 *   --sessions N       parallel Claude API sessions (1–10, default 1)
 *   --limit N          max pages to process in this run
 *   --max-impressions N pages with impressions > N are skipped (default 0)
 */
class LauncherImprove : public AbstractLauncher
{
public:
    static const QString OPTION_NAME;
    static const QString OPTION_SESSIONS;
    static const QString OPTION_LIMIT;
    static const QString OPTION_MAX_IMPRESSIONS;

    QString getOptionName() const override;
    bool    isFlag()        const override;
    void    run(const QString &value) override;
};

#endif // LAUNCHERIMPROVE_H
