# Generated by Django 6.0.4 on 2026-07-11 12:56

import badges.models
import django.db.models.deletion
import media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Admin label only, e.g. 'Safe checkout'.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "preset_key",
                    models.CharField(
                        help_text="Key into badges.badge_presets.BADGE_PRESETS, or 'custom'.",
                        max_length=40,
                    ),
                ),
                (
                    "custom_image",
                    models.ImageField(
                        blank=True,
                        help_text="Used only when preset_key='custom'. Raster only (PNG/JPEG/WebP) — no SVG.",
                        null=True,
                        upload_to="security_badges/%Y/%m/",
                        validators=[
                            media.validators.validate_image_file,
                            badges.models.validate_custom_image_not_svg,
                        ],
                    ),
                ),
                ("heading_enabled", models.BooleanField(default=True)),
                (
                    "heading_segments_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"text": "Guaranteed", "color": "#000000"}, ...] — at most 6 segments.',
                    ),
                ),
                ("border_enabled", models.BooleanField(default=True)),
                ("border_color", models.CharField(default="#000000", max_length=7)),
                ("border_width_px", models.PositiveSmallIntegerField(default=5)),
                (
                    "locations_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"product": {"enabled": false, "width_px": 200}, "cart": {"enabled": false, "width_px": 200}, "checkout": {"enabled": true, "width_px": 200}}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "security badge",
                "verbose_name_plural": "security badges",
                "indexes": [
                    models.Index(
                        fields=["store", "is_active"],
                        name="badges_secu_store_i_d29980_idx",
                    )
                ],
            },
        ),
    ]
