set(COMMONBLOCS_WIDGETS_FILES
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocHeader.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocHeader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocHeader.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocFooter.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocFooter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocFooter.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocCookies.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocCookies.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocCookies.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocAiDisclaimer.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocAiDisclaimer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocAiDisclaimer.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocSearch.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocSearch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocSearch.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogMenuItemEdit.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogMenuItemEdit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogMenuItemEdit.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogPickPage.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogPickPage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogPickPage.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocMenu.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocMenu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetCommonBlocMenu.ui
)
