set(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDomains.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDomains.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDomains.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMenus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMenus.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMenus.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGeneration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGeneration.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGeneration.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/GenStrategyTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/GenStrategyTable.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneUpdate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneUpdate.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneUpdate.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/UpdateStrategyTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/UpdateStrategyTree.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePages.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePages.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePages.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGeneratedPages.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGeneratedPages.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGeneratedPages.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePageStats.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePageStats.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePageStats.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTranslations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTranslations.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTranslations.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTheme.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTheme.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTheme.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/widgets/WidgetEditCommonBlocs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/widgets/WidgetEditCommonBlocs.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/widgets/WidgetEditCommonBlocs.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddGeneration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddGeneration.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddGeneration.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogGeneratePhase2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogGeneratePhase2.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogGeneratePhase2.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddUpdateStrategy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddUpdateStrategy.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddUpdateStrategy.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddUpdatePrompt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddUpdatePrompt.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddUpdatePrompt.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogShowCommand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogShowCommand.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogShowCommand.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickArticlesToReset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickArticlesToReset.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickArticlesToReset.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickArticlesToUpdate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickArticlesToUpdate.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickArticlesToUpdate.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewUpdatedArticles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewUpdatedArticles.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewUpdatedArticles.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickEngine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickEngine.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickEngine.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditHosts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditHosts.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditHosts.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPreviewPage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPreviewPage.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPreviewPage.ui
)
