set(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDomains.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDomains.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDomains.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMenus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMenus.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMenus.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePages.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePages.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePages.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePageStats.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePageStats.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePageStats.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTheme.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTheme.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneTheme.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/widgets/WidgetEditCommonBlocs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/widgets/WidgetEditCommonBlocs.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/widgets/WidgetEditCommonBlocs.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickEngine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickEngine.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickEngine.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditHosts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditHosts.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditHosts.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPreviewPage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPreviewPage.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPreviewPage.ui
)
