# Generated by Django 6.0.4 on 2026-07-11 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aijobs", "0004_alter_aijob_job_type"),
        ("customers", "0001_initial"),
        ("discounts", "0004_alter_discountcode_times_used"),
        ("permalinks", "0005_alter_permalink_slug"),
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadCaptureCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("exit", "Exit"), ("time", "Time")],
                        default="exit",
                        max_length=10,
                    ),
                ),
                (
                    "trigger_delay_seconds",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Used when trigger='time'. ASSUMPTION (ADR-027 D2): screenshot hides this input until 'Time' is selected.",
                    ),
                ),
                (
                    "mobile_trigger",
                    models.CharField(
                        choices=[("disabled", "Disabled"), ("time", "Time")],
                        default="disabled",
                        max_length=10,
                    ),
                ),
                (
                    "mobile_trigger_delay_seconds",
                    models.PositiveIntegerField(default=15),
                ),
                (
                    "overlay_theme_key",
                    models.CharField(
                        default="centered_light",
                        help_text="Key into engagement.themes.OVERLAY_THEMES.",
                        max_length=50,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="SIGN-UP FOR OUR NEWSLETTER", max_length=255
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        blank=True, default="AND GET A 10% OFF COUPON", max_length=500
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(default="GET MY 10% OFF NOW", max_length=100),
                ),
                (
                    "dismiss_label",
                    models.CharField(
                        blank=True, default="I don't want to save money", max_length=150
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        blank=True,
                        default="Thanks for signing up! Here is your code: {code}",
                        help_text="Supports a {code} placeholder, substituted server-side (ADR-027 D3 step 6). Ignored when no reward_discount_code is configured (the {code} token is simply left blank).",
                    ),
                ),
                (
                    "post_signup_action",
                    models.CharField(
                        choices=[
                            ("display_message", "Display message"),
                            ("go_to_url", "Go to Url"),
                        ],
                        default="display_message",
                        max_length=20,
                    ),
                ),
                ("redirect_url", models.URLField(blank=True, default="")),
                ("cap_enabled", models.BooleanField(default=False)),
                ("cap_impressions", models.PositiveIntegerField(default=1)),
                ("cap_window_value", models.PositiveIntegerField(default=1)),
                (
                    "cap_window_unit",
                    models.CharField(
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        default="minutes",
                        max_length=10,
                    ),
                ),
                (
                    "signup_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of string tags appended to Customer.tags on signup (TICKET-011 tags contract).",
                    ),
                ),
                ("visitors_count", models.PositiveIntegerField(default=0)),
                ("impressions_count", models.PositiveIntegerField(default=0)),
                ("conversions_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "excluded_pages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pages that suppress this overlay for a visitor who browsed them. Resolved to a path list (all active languages of the same page) at render time — never store raw path strings (ADR-027 D2/D4).",
                        related_name="excluding_lead_capture_campaigns",
                        to="permalinks.permalink",
                    ),
                ),
                (
                    "reward_discount_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing coupon/gift-card code issued to every signup (shared code — abuse bounded at redemption by per_email_limit, ADR-002 §4).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lead_capture_campaigns",
                        to="discounts.discountcode",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "lead capture campaign",
                "verbose_name_plural": "lead capture campaigns",
            },
        ),
        migrations.CreateModel(
            name="LeadCaptureCampaignTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang_code", models.CharField(max_length=10)),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("body", models.CharField(blank=True, max_length=500)),
                ("cta_label", models.CharField(blank=True, max_length=100)),
                ("dismiss_label", models.CharField(blank=True, max_length=150)),
                ("success_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_capture_campaign_translations",
                        to="aijobs.aijob",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="engagement.leadcapturecampaign",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "lead capture campaign translation",
                "verbose_name_plural": "lead capture campaign translations",
            },
        ),
        migrations.CreateModel(
            name="LeadSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "lang",
                    models.CharField(
                        help_text="Language the overlay was shown in.", max_length=10
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the double opt-in confirmation link is clicked (DE-targeting stores only). Null for single opt-in signups.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="PROTECT — the signup is the audit/consent-proof trail.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signups",
                        to="engagement.leadcapturecampaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_signups",
                        to="customers.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "lead signup",
                "verbose_name_plural": "lead signups",
            },
        ),
        migrations.CreateModel(
            name="SocialProofSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("anonymous", "Anonymous"),
                            ("first_name", "First name"),
                            ("first_name_city", "First name + city"),
                        ],
                        default="anonymous",
                        max_length=20,
                    ),
                ),
                (
                    "window_hours",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "first_delay_seconds",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "max_items",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("bottom_left", "Bottom left"),
                            ("bottom_right", "Bottom right"),
                        ],
                        default="bottom_left",
                        max_length=20,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "social proof settings",
                "verbose_name_plural": "social proof settings",
            },
        ),
        migrations.AddIndex(
            model_name="leadcapturecampaign",
            index=models.Index(
                fields=["store", "is_active", "-created_at"],
                name="engagement_lcc_active_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leadcapturecampaigntranslation",
            unique_together={("store", "campaign", "lang_code")},
        ),
        migrations.AddIndex(
            model_name="leadsignup",
            index=models.Index(
                fields=["store", "campaign", "email"], name="engagement_signup_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leadsignup",
            unique_together={("store", "campaign", "email")},
        ),
    ]
