# Generated by Django 6.0.4 on 2026-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="socialproofsettings",
            constraint=models.UniqueConstraint(
                fields=("store",), name="unique_social_proof_settings_per_store"
            ),
        ),
    ]
