# Generated by Django 6.0.4 on 2026-07-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sentemail",
            new_name="emails_sent_store_i_d4987f_idx",
            old_name="emails_sent_store_i_e01234_idx",
        ),
        migrations.RenameIndex(
            model_name="sentemail",
            new_name="emails_sent_order_i_8e4918_idx",
            old_name="emails_sent_order_i_e01235_idx",
        ),
    ]
