# Generated by Django 6.0.4 on 2026-07-11 20:38

import django.db.models.deletion
import payments.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emails",
            "0002_rename_emails_sent_store_i_e01234_idx_emails_sent_store_i_d4987f_idx_and_more",
        ),
        ("stores", "0012_alter_organization_coverage_areas_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SenderDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Fully qualified domain to send email from (e.g. shop.example.com). Globally unique across all stores.",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending verification"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="unverified",
                        max_length=10,
                    ),
                ),
                (
                    "sender_local_part",
                    models.CharField(
                        default="noreply",
                        help_text="Mailbox part of the From address, e.g. 'noreply' in noreply@shop.example.com.",
                        max_length=64,
                    ),
                ),
                (
                    "dkim_selector",
                    models.CharField(
                        default="pradize1",
                        help_text="DKIM selector — published at '<selector>._domainkey.<domain>'.",
                        max_length=63,
                    ),
                ),
                (
                    "dkim_private_key",
                    payments.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Platform-generated RSA private key (PEM, PKCS8), encrypted at rest. Never displayed in admin.",
                    ),
                ),
                (
                    "dkim_public_key",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Base64 DER public key body (no PEM headers) — published verbatim in the DKIM TXT record's 'p=' tag. Not secret.",
                    ),
                ),
                (
                    "verification_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of DNS check attempts since the last mark_pending().",
                    ),
                ),
                (
                    "pending_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this domain last entered PENDING — anchors the attempt/time budget.",
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_check_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable detail from the most recent DNS check (any status).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_domains",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "sender domain",
                "verbose_name_plural": "sender domains",
            },
        ),
        migrations.CreateModel(
            name="SenderDomainManualVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending verification"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_verifications",
                        to="emails.senderdomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "sender domain manual verification",
                "verbose_name_plural": "sender domain manual verifications",
                "ordering": ["-performed_at"],
            },
        ),
    ]
