# Generated by Django 6.0.4 on 2026-07-11 22:39

import django.core.validators
import emails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_senderdomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senderdomain",
            name="sender_local_part",
            field=models.CharField(
                default="noreply",
                help_text="Mailbox part of the From address, e.g. 'noreply' in noreply@shop.example.com. Mailbox-safe characters only (letters, digits, and . _ % + -).",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9._%+-]+$",
                        "Mailbox-safe characters only (letters, digits, and . _ % + -). Spaces, '@', and control characters are not allowed.",
                    ),
                    emails.models.validate_no_crlf,
                ],
            ),
        ),
    ]
