# Generated by Django 6.0.4 on 2026-07-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_fix_sku_constraint_per_store"),
        ("stores", "0006_storedomain_storelanguage_shippingcountry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "tracking_url_template",
                    models.CharField(
                        blank=True,
                        help_text="URL template with {tracking_number} placeholder. e.g. https://tracking.ups.com/track/{tracking_number}",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "shipping carrier",
                "verbose_name_plural": "shipping carriers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country_codes",
                    models.JSONField(
                        default=list,
                        help_text="ISO 3166-1 alpha-2 codes. Empty list = 'All Countries' catch-all zone.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "shipping zone",
                "verbose_name_plural": "shipping zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name shown to buyer, e.g. "Standard Shipping", "Express".',
                        max_length=100,
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate"),
                            ("weight", "Weight Based"),
                            ("free", "Free Shipping"),
                            ("carrier", "Carrier Calculated"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Flat/free price. Set to 0 for FREE rate type.",
                        max_digits=10,
                    ),
                ),
                (
                    "min_weight_grams",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum weight in grams for WEIGHT_BASED rates.",
                    ),
                ),
                (
                    "max_weight_grams",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum weight in grams for WEIGHT_BASED rates. Null = no upper bound.",
                        null=True,
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rates",
                        to="shipping.shippingcarrier",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping rate",
                "verbose_name_plural": "shipping rates",
            },
        ),
        migrations.CreateModel(
            name="ShippingRateException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The overriding shipping price for this exception.",
                        max_digits=10,
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[("product", "Product"), ("collection", "Collection")],
                        max_length=50,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_exceptions",
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_exceptions",
                        to="catalog.product",
                    ),
                ),
                (
                    "shipping_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="shipping.shippingrate",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping rate exception",
                "verbose_name_plural": "shipping rate exceptions",
            },
        ),
    ]
