# Generated by Django 6.0.4 on 2026-07-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_seed_carriers_and_catchall_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="service_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional customer-facing note shown at checkout for rates in this zone, e.g. 'Ships from EU warehouse — no customs'. Shared by ALL stores shipping to this zone — keep it operational and store-neutral, never store-branded.",
            ),
        ),
    ]
