set(TAXONOMY_FILES
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyPageSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyPageSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyDescriptor.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyDb.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyDb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomySettings.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomySettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyTranslator.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyTranslator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyTranslationFilter.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxonomyTranslationFilter.cpp
)
