# Generated by Django 6.0.4 on 2026-07-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_processoraccount_full_model"),
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=100,
                        help_text="Lower value = evaluated first. Rules are ordered ascending by this field.",
                    ),
                ),
                (
                    "store_currency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Match orders in this ISO 4217 currency. Blank = match any currency.",
                        max_length=3,
                    ),
                ),
                (
                    "store_primary_language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Match orders from stores whose primary_language equals this value. Blank = match any language.",
                        max_length=10,
                    ),
                ),
                (
                    "min_amount_cents",
                    models.IntegerField(
                        blank=True,
                        help_text="Match orders whose total >= this amount in cents. Null = no lower bound.",
                        null=True,
                    ),
                ),
                (
                    "max_amount_cents",
                    models.IntegerField(
                        blank=True,
                        help_text="Match orders whose total <= this amount in cents. Null = no upper bound.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_organization",
                    models.ForeignKey(
                        help_text="Organization whose ProcessorAccount(s) will be used when this rule matches.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_rules",
                        to="stores.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "routing rule",
                "verbose_name_plural": "routing rules",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Soft reference to orders.Order.pk — not a FK so the log survives order deletion.",
                    ),
                ),
                (
                    "store_id",
                    models.IntegerField(
                        help_text="Soft reference to stores.Store.pk — not a FK."
                    ),
                ),
                (
                    "was_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="True when no rule matched and the default Organization was used.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Machine-readable reason code: 'rule_match', 'fallback_default_org', or 'routing_failure'.",
                        max_length=255,
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_account",
                    models.ForeignKey(
                        help_text="ProcessorAccount that was selected. Null on routing failure.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_decisions",
                        to="payments.processoraccount",
                    ),
                ),
                (
                    "selected_organization",
                    models.ForeignKey(
                        help_text="Organization whose account was selected. Null on routing failure.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_decisions",
                        to="stores.organization",
                    ),
                ),
                (
                    "matched_rule",
                    models.ForeignKey(
                        help_text="RoutingRule that triggered the decision. Null for fallback and failure rows.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_decisions",
                        to="payments.routingrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "decision log",
                "verbose_name_plural": "decision logs",
                "ordering": ["-decided_at"],
            },
        ),
    ]
