# Generated by Django 6.0.4 on 2026-07-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_routing_rebuild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationrule",
            name="fallback_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Next rule to evaluate when this rule's outcome is ineligible. NULL = fall through to the default org. Must not form a cycle.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fallback_sources",
                to="payments.organizationrule",
            ),
        ),
        migrations.AlterField(
            model_name="processoraccount",
            name="method_family",
            field=models.CharField(
                choices=[("card", "card"), ("paypal", "paypal"), ("crypto", "crypto")],
                default="card",
                help_text="Which checkout method family this account can process. Stripe accounts = card; PayPal = paypal. PayPal-as-card capability: create a second row with method_family='card'.",
                max_length=20,
            ),
        ),
    ]
