# Generated by Django 6.0.4 on 2026-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_organizationrule_fallback_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoraccount",
            name="paypal_capture_mode",
            field=models.CharField(
                choices=[
                    ("delayed", "Delayed (authorize, then capture — funnel-eligible)"),
                    ("immediate", "Immediate capture (skip post-purchase funnel)"),
                ],
                default="delayed",
                help_text="PayPal only. Delayed = Orders API intent=AUTHORIZE; immediate = intent=CAPTURE. Immediate-capture orders are funnel-ineligible (no capture window, no upsell).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processoraccount",
            name="paypal_vault_enabled",
            field=models.BooleanField(
                default=False,
                help_text="PayPal only. True once the merchant has completed PayPal Vault onboarding (reference-transaction / vaulting agreement). Off-session upsell charges — and therefore post-purchase funnel eligibility for PayPal-routed orders — require this. False = PayPal orders are funnel-ineligible regardless of capture mode (prevents a silent 100%-failure funnel, ADR-011 Q3 §XV-1).",
            ),
        ),
    ]
