# Generated by Django 6.0.4 on 2026-07-11 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
        ("stores", "0011_store_checkout_phone_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("non_eu_acknowledged", models.BooleanField(default=False)),
                ("non_eu_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("beacon_requires_consent", models.BooleanField(default=False)),
                (
                    "non_eu_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.staticpage",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent settings",
                "verbose_name_plural": "Consent settings",
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_id", models.UUIDField(db_index=True)),
                ("analytics", models.BooleanField(default=False)),
                ("marketing", models.BooleanField(default=False)),
                ("am_objected", models.BooleanField(default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("accept_all", "Accept all"),
                            ("refuse_all", "Refuse all"),
                            ("custom", "Custom"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=16,
                    ),
                ),
                ("policy_version", models.PositiveSmallIntegerField()),
                ("lang", models.CharField(max_length=8)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("manage_panel", "Manage panel"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent record",
                "verbose_name_plural": "Consent records",
                "indexes": [
                    models.Index(
                        fields=["store", "created_at"],
                        name="consent_rec_store_created_idx",
                    )
                ],
            },
        ),
    ]
