# Generated by Django 6.0.4 on 2026-07-11 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0001_initial"),
        ("pages", "0001_initial"),
        ("stores", "0011_store_checkout_phone_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="consentsettings",
            constraint=models.UniqueConstraint(
                fields=("store",), name="unique_consent_settings_per_store"
            ),
        ),
    ]
