# Generated by Django 6.0.4 on 2026-07-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pixel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("facebook", "Meta / Facebook Pixel"),
                            ("ga", "Google Analytics 4"),
                            ("tiktok", "TikTok Pixel"),
                            ("snapchat", "Snapchat Pixel"),
                            ("pinterest", "Pinterest Tag"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pixel_id",
                    models.CharField(
                        help_text="Provider-issued pixel/measurement ID. Format is validated per provider.",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Installed pixels only render while active. Deactivate to uninstall.",
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reserved for future use (e.g. CAPI token, consent category). Unread in v1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "pixel",
                "verbose_name_plural": "pixels",
                "indexes": [
                    models.Index(
                        fields=["store", "is_active"],
                        name="pixels_pixe_store_i_218c16_idx",
                    )
                ],
                "unique_together": {("store", "provider")},
            },
        ),
    ]
