# Stub migration — restores the bare Order table that discounts.0002_initial depends on.
# The full Order schema plus OrderItem, OrderFulfillment, FiredPixel are added by
# 0002_full_schema (generated by makemigrations orders after this file exists).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "abstract": False,
            },
        ),
    ]
