# Generated by Django 6.0.4 on 2026-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_full_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="processor_charge_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Charge/transaction ID after capture; used for refund targeting.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="processor_payment_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stripe PaymentIntent ID (or equivalent) set at checkout.",
                max_length=255,
            ),
        ),
    ]
