# Generated by Django 6.0.4 on 2026-07-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_processor_intent_charge_ids"),
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("original", "Original"), ("upsell", "Upsell")],
                        default="original",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="authorized",
                        max_length=20,
                    ),
                ),
                (
                    "processor_payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe PaymentIntent ID (or PayPal authorization ID) for this charge.",
                        max_length=255,
                    ),
                ),
                (
                    "processor_charge_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Charge/transaction ID after capture; used for refund targeting.",
                        max_length=255,
                    ),
                ),
                (
                    "amount_cents",
                    models.IntegerField(
                        default=0,
                        help_text="Amount in smallest currency unit (cents), mirroring the processor interface.",
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="orders.order",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "order charge",
                "verbose_name_plural": "order charges",
                "indexes": [
                    models.Index(
                        fields=["order"], name="orders_orde_order_i_c24787_idx"
                    ),
                    models.Index(
                        fields=["processor_payment_intent_id"],
                        name="orders_orde_process_b2b456_idx",
                    ),
                ],
            },
        ),
    ]
