# Generated by Django 6.0.4 on 2026-07-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0002_initial"),
        ("orders", "0005_order_gift_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Coupon applied to this order (ADR-002 §3 — coupon first).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="discounts.discountcode",
            ),
        ),
    ]
