# Generated by Django 6.0.4 on 2026-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_model_gaps"),
        ("stores", "0009_alter_store_custom_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="processor_customer_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe cus_… / PayPal payer ID set at checkout for off-session upsell charges (ADR-011 Q4). Blank for guest orders and non-vault processors.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="processor_payment_method_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe pm_… / PayPal vault token ID set at checkout authorization. Required for off-session upsell charges (ADR-011 Q4). Not a secret — unusable without merchant credentials. Excluded from admin list displays and logs.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="ordercharge",
            name="campaign_step_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Soft reference (no FK) to campaigns.CampaignStep.pk. Set on UPSELL charges; null for ORIGINAL. Partial unique (order, campaign_step_id) WHERE non-null prevents double charges per step per order (ADR-011 Q1 idempotency backstop).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordercharge",
            name="capture_claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the watchdog claims this charge for capture (AUTHORIZED → CAPTURE_IN_PROGRESS). Null when not yet claimed. ADR-011 Q1 / ADR-007 §6b.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending_capture", "Pending Capture"),
                    ("voided", "Voided"),
                    ("failed", "Failed"),
                ],
                default="active",
                help_text="Per-item lifecycle for upsell provisional items (ADR-011). ACTIVE = confirmed; PENDING_CAPTURE = provisional (excluded from fulfilment); VOIDED = window expired without capture; FAILED = upsell charge declined.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordercharge",
            name="status",
            field=models.CharField(
                choices=[
                    ("authorized", "Authorized"),
                    ("capture_in_progress", "Capture In Progress"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="authorized",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="ordercharge",
            index=models.Index(fields=["status"], name="ordercharge_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="ordercharge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("processor_charge_id__gt", "")),
                fields=("processor_charge_id",),
                name="ordercharge_unique_processor_charge_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordercharge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("campaign_step_id__isnull", False)),
                fields=("order", "campaign_step_id"),
                name="ordercharge_unique_order_campaign_step",
            ),
        ),
    ]
