# Generated by Django 6.0.4 on 2026-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_ordercharge_breach_alerted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercharge",
            name="status",
            field=models.CharField(
                choices=[
                    ("authorized", "Authorized"),
                    ("capture_in_progress", "Capture In Progress"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("ambiguous_outcome", "Ambiguous Outcome"),
                ],
                default="authorized",
                max_length=30,
            ),
        ),
    ]
