# Generated by Django 6.0.4 on 2026-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_checkout_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="capture_immediately",
            field=models.BooleanField(
                default=False,
                help_text="True when no funnel campaign applied at checkout — the order is captured immediately on payment confirmation rather than waiting for the capture-window watchdog (20:P1). capture_window_expires_at remains set as the watchdog fallback if the inline capture fails.",
            ),
        ),
    ]
