# Generated by Django 6.0.4 on 2026-07-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_retire_purchase_guard_sentinel"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="page_version_id",
            field=models.IntegerField(
                blank=True,
                help_text="Soft ID snapshot of CartItem.page_version_id at order creation (NULL = primary page). Not an FK (ADR-028 §1).",
                null=True,
            ),
        ),
    ]
