# Generated by Django 6.0.4 on 2026-07-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of string tags; used by lead capture campaigns.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "is_verified_buyer",
                    models.BooleanField(
                        default=False,
                        help_text="True once the customer has at least one paid order.",
                    ),
                ),
                ("accepts_marketing", models.BooleanField(default=False)),
                (
                    "anonymized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when this customer record has been anonymized for GDPR.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code, e.g. 'US', 'FR'.",
                        max_length=2,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "customer address",
                "verbose_name_plural": "customer addresses",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["store", "email"], name="customers_c_store_i_a90b8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["store", "created_at"], name="customers_c_store_i_4c5bf4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("store", "email")},
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["customer"], name="customers_c_custome_5f7ed5_idx"
            ),
        ),
    ]
