# Generated by Django 6.0.4 on 2026-07-04 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aijobs", "0004_alter_aijob_job_type"),
        ("catalog", "0004_fix_sku_constraint_per_store"),
        ("orders", "0007_order_model_gaps"),
        ("stores", "0008_populate_store_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(blank=True, max_length=100)),
                (
                    "reviewer_email",
                    models.CharField(
                        blank=True,
                        help_text="Internal only — never rendered publicly. Used for verified-buyer check.",
                        max_length=254,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Star rating from 1 (lowest) to 5 (highest).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("spam", "Spam"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("ai_generated", "AI Generated"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified_buyer",
                    models.BooleanField(
                        default=False,
                        help_text="True when reviewer_email matches a paid order containing this product. Set once at submission time; never recomputed.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The AI job that generated this review (AI_GENERATED provenance only).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="aijobs.aijob",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin user who last changed the review status.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The order that generated this review (set for customer-submitted reviews).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "indexes": [
                    models.Index(
                        fields=["store", "product", "status"],
                        name="reviews_rev_store_i_1a87e4_idx",
                    ),
                    models.Index(
                        fields=["store", "status", "submitted_at"],
                        name="reviews_rev_store_i_67e0a4_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="review_rating_1_to_5",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="When to send the review-request email (order shipment time + delay_days)."
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "review request",
                "verbose_name_plural": "review requests",
                "indexes": [
                    models.Index(
                        fields=["is_sent", "scheduled_at"],
                        name="reviews_rev_is_sent_ad1cbd_idx",
                    )
                ],
            },
        ),
    ]
