include(${CMAKE_CURRENT_LIST_DIR}/shortcodes/shortcodes.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/pages/pages.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/commonblocs/commonblocs.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/theme/theme.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/perf/perf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/translation/translation.cmake)

set(WEBSITE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/WebCodeAdder.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractEngine.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractEngine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImageWriter.h
    ${CMAKE_CURRENT_LIST_DIR}/ImageWriter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HostTable.h
    ${CMAKE_CURRENT_LIST_DIR}/HostTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineLanguages.h
    ${CMAKE_CURRENT_LIST_DIR}/EngineLanguages.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineArticles.h
    ${CMAKE_CURRENT_LIST_DIR}/EngineArticles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WebsiteSettingsTable.h
    ${CMAKE_CURRENT_LIST_DIR}/WebsiteSettingsTable.cpp
    ${SHORTCODES_FILES}
    ${PAGES_FILES}
    ${COMMONBLOCS_FILES}
    ${THEME_FILES}
    ${PERF_FILES}
    ${TRANSLATION_FILES}
)
