# Generated by Django 6.0.4 on 2026-07-03 03:23

import catalog.validators
import django.db.models.deletion
import media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(blank=True, max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        validators=[catalog.validators.validate_video_url],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/%Y/%m/",
                        validators=[media.validators.validate_image_file],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(default="Default", max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(default=0)),
                (
                    "inventory_mode",
                    models.CharField(
                        choices=[
                            ("sold_out", "Sold out (always)"),
                            ("no_tracking", "No inventory tracking"),
                            ("fixed_qty", "Track fixed quantity"),
                            ("fake_server", "Server-assigned display (fake scarcity)"),
                            ("presale", "Pre-sale (charge on placement)"),
                            ("ask_when_available", "Ask me when available"),
                            ("quotation", "Ask for quotation"),
                        ],
                        default="no_tracking",
                        max_length=32,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("presale_ships_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "product variant",
                "verbose_name_plural": "product variants",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["store", "status"], name="catalog_pro_store_i_0b8c66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["store", "updated_at"], name="catalog_pro_store_i_a97ef3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("store", "slug")},
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="catalog_pro_product_c9ec4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["store", "inventory_mode"],
                name="catalog_pro_store_i_d64789_idx",
            ),
        ),
    ]
