# Generated by Django 6.0.4 on 2026-07-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(blank=True, max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "collection_type",
                    models.CharField(
                        choices=[("smart", "Smart (auto)"), ("manual", "Manual")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="collections/%Y/%m/"
                    ),
                ),
                (
                    "smart_rules",
                    models.JSONField(
                        default=list,
                        help_text='List of rule dicts: [{"field": "title|price|tag", "op": "contains|equals|greater_than|less_than|starts_with", "value": "..."}]. Evaluated by catalog/smart_rules.py. Price uses base price only (v1).',
                    ),
                ),
                (
                    "smart_rules_match",
                    models.CharField(
                        choices=[("all", "All conditions"), ("any", "Any condition")],
                        default="all",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
            },
        ),
        migrations.CreateModel(
            name="CollectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_key",
                    models.CharField(
                        default="",
                        help_text="Stable lexicographic ordering key. Never renumbered on sibling removal. Use fractional indexing strings for manual drag-ordering.",
                        max_length=255,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "collection product",
                "verbose_name_plural": "collection products",
                "ordering": ["sort_key"],
            },
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["store", "is_published"], name="catalog_col_store_i_a305e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("store", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="collectionproduct",
            unique_together={("collection", "product")},
        ),
    ]
