# Generated by Django 6.0.4 on 2026-07-03 08:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_collection_collectionproduct_and_more"),
        ("stores", "0004_organization_routing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="option_values_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="position",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("sku"),
                condition=models.Q(("sku", ""), _negated=True),
                name="variant_sku_case_insensitive_unique",
            ),
        ),
    ]
