# Generated by Django 6.0.4 on 2026-07-03 08:41

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_variant_options_product_fields"),
        ("stores", "0005_store_password_protection"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="variant_sku_case_insensitive_unique",
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("sku"),
                models.F("store"),
                condition=models.Q(("sku", ""), _negated=True),
                name="variant_sku_case_insensitive_per_store",
            ),
        ),
    ]
