# Generated by Django 6.0.4 on 2026-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_add_source_fingerprint_to_translation_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttranslation",
            name="slug_hint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Suggested slug from AI slug_only job. Used as the initial slug for the auto-created Permalink; updated automatically when the signal fires.",
                max_length=255,
            ),
        ),
    ]
