# Generated by Django 6.0.4 on 2026-07-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_stock_notification_quotation_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationrequest",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL = general (non-product) quotation request (ADR-018 D4).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_requests",
                to="catalog.product",
            ),
        ),
    ]
