# Generated by Django 6.0.4 on 2026-07-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_quotation_request_nullable_product"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stocknotification",
            new_name="catalog_stkn_store_ntfy_idx",
            old_name="catalog_stkn_store_notified_idx",
        ),
    ]
