# Generated by Django 6.0.4 on 2026-07-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_fix_stocknotification_index_name_length"),
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal admin label (e.g. 'Model 2 photos'). Never rendered to shoppers.",
                        max_length=255,
                    ),
                ),
                (
                    "slug_suffix",
                    models.CharField(
                        help_text="Appended to the product slug: <product-slug>-<suffix>. Normalized via make_slug().",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive versions 302-redirect their URL(s) to the primary product page.",
                    ),
                ),
                (
                    "position",
                    models.SmallIntegerField(
                        default=0, help_text="Admin display ordering (ascending)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_versions",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "product page version",
                "verbose_name_plural": "product page versions",
                "ordering": ["position", "pk"],
                "unique_together": {("product", "slug_suffix")},
            },
        ),
        migrations.CreateModel(
            name="ProductPageVersionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_version_uses",
                        to="catalog.productimage",
                    ),
                ),
                (
                    "page_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productpageversion",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "product page version image",
                "verbose_name_plural": "product page version images",
                "ordering": ["display_order"],
                "unique_together": {("page_version", "image")},
            },
        ),
    ]
