# Generated by Django 6.0.4 on 2026-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_productpageversion_productpageversionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
