set(ASPIRE_ATTRIBUTES_FASHION_FILES
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionProductType.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionProductType.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionColorFamily.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionColorFamily.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionColor.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionColor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionSeason.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionSeason.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionStyleAesthetic.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionStyleAesthetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionFitSilhouette.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionFitSilhouette.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionMaterial.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionMaterial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionPattern.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionPattern.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionDemographic.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionDemographic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionCulture.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionCulture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboBase.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorProduct.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorProduct.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboSeasonEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboSeasonEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboFitProductDemographic.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboFitProductDemographic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorProductEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorProductEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboMaterialProductSeason.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboMaterialProductSeason.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboFitProductEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboFitProductEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleSeason.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleSeason.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorColor.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorColor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductPattern.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductPattern.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleProduct.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleProduct.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorSeason.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorSeason.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductDemographic.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductDemographic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboMaterialProduct.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboMaterialProduct.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleProductEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboStyleProductEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorProductDemographic.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboColorProductDemographic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductDemographicEvent.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboProductDemographicEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboPatternProductSeason.h
    ${CMAKE_CURRENT_LIST_DIR}/PageAttributesFashionComboPatternProductSeason.cpp
)
