# Generated by Django 6.0.4 on 2026-07-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_order_model_gaps"),
        ("stores", "0008_populate_store_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("abandoned_checkout", "Abandoned checkout"),
                            ("related_products", "Related products"),
                            ("buy_x_get_x", "Buy X get X"),
                            ("storewide_discount", "Storewide discount"),
                            ("one_click_funnel", "One-click funnel"),
                            ("order_bump", "Order bump"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "targeting_rules_json",
                    models.JSONField(
                        default=dict,
                        help_text="Eligibility and exclusion rules evaluated at funnel entry. Keys vary by rule type; Phase 1 ignores this field and returns all active campaigns of the type (see campaigns/service.py).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign",
                "verbose_name_plural": "campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("impression", "Impression"),
                            ("interaction", "Interaction"),
                            ("converted", "Converted"),
                            ("dismissed", "Dismissed"),
                            ("expired", "Expired"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "recovery_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text=(
                            "Revenue attributed to this session's conversion. "
                            "Non-zero only when INTERACTION was reached or an attributed coupon was redeemed."
                        ),
                        max_digits=12,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        help_text="Set when a shopper clicks the resume link (IMPRESSION → INTERACTION).",
                    ),
                ),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "Denormalized copy of Order.capture_window_expires_at. "
                            "Set at session creation; used to evaluate eligibility without a JOIN. "
                            "Not used for abandoned-checkout sessions (those use abandoned_at + 30d)."
                        ),
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_sessions",
                        to="orders.order",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign session",
                "verbose_name_plural": "campaign sessions",
            },
        ),
        migrations.CreateModel(
            name="CampaignSessionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("thankyou-view", "Thank-you view"),
                            ("upsell-act", "Upsell act"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the raw token. Raw value is never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the token is consumed. Null = not yet used.",
                        null=True,
                    ),
                ),
                (
                    "campaign_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="campaigns.campaignsession",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign session token",
                "verbose_name_plural": "campaign session tokens",
            },
        ),
        migrations.CreateModel(
            name="CampaignStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Display order within the campaign. Gaps are allowed; this field is never renumbered (§VII)."
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("related_products", "Related products"),
                            ("buy_x_get_x", "Buy X get X"),
                            ("storewide_discount", "Storewide discount"),
                            ("one_click_funnel", "One-click funnel"),
                            ("order_bump", "Order bump"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "offer_config_json",
                    models.JSONField(
                        default=dict,
                        help_text="Archetype-specific offer configuration (product IDs, discount %, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accept_next_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Step shown after the buyer accepts this offer. Null = terminal (converted).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campaigns.campaignstep",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "decline_next_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Step shown after the buyer declines this offer. Null = terminal (dismissed).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campaigns.campaignstep",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign step",
                "verbose_name_plural": "campaign steps",
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="campaignsession",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_sessions",
                to="campaigns.campaignstep",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["store", "campaign_type", "is_active"],
                name="campaigns_c_store_i_a5ef74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["store", "created_at"], name="campaigns_c_store_i_85fdd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignsessiontoken",
            index=models.Index(
                fields=["store", "expires_at"], name="campaigns_c_store_i_c5048f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignstep",
            index=models.Index(
                fields=["campaign", "position"], name="campaigns_c_campaig_203fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignsession",
            index=models.Index(
                fields=["store", "state"], name="campaigns_c_store_i_38aec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignsession",
            index=models.Index(
                fields=["store", "created_at"], name="campaigns_c_store_i_85e3c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignsession",
            index=models.Index(
                fields=["campaign", "state"], name="campaigns_c_campaig_0ce87e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignsession",
            unique_together={("order", "campaign")},
        ),
    ]
