# Generated by Django 6.0.4 on 2026-07-05 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_abandoned_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abandonedcheckoutemailstep",
            name="send_delay_hours",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Hours from session.abandoned_at before this email is sent. Must be >= 1. Days-unit form input is stored as hours × 24. Measured from abandoned_at for all steps (ADR-010 ASSUMPTION). Delays are checked every 5 minutes — actual send time may be up to 5 minutes later than configured.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
