# Generated by Django 6.0.4 on 2026-07-05 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_email_step_delay_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="capture_window_minutes",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Minutes from authorization to capture-window expiry (ADR-011 Q5). Applied at checkout: Order.capture_window_expires_at = authorized_at + minutes. Meaningful only for funnel-type campaigns. Range: 1–60 minutes.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AddField(
            model_name="campaignsession",
            name="accept_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Count of upsell accept attempts for this session. Incremented on every accept call; capped at 5 (UpsellRateLimitError on 6th+). DB-backed for process-restart safety (ADR-011).",
            ),
        ),
    ]
