# Generated by Django 6.0.4 on 2026-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_campaignsession_data_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsessiontoken",
            name="offered_amount_cents",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Amount shown to the customer at token-issue time (M3 guard). Checked at accept to prevent post-issue admin price edits from charging an amount the customer never saw. Null = storewide_discount step or no charge (guard skipped).",
                null=True,
            ),
        ),
    ]
