# Generated by Django 6.0.4 on 2026-07-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AggregatedMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(db_index=True, max_length=100)),
                ("store_id", models.IntegerField(db_index=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "dimension_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store_id", "metric_type", "period_start"],
                        name="analytics_a_store_i_7e0b92_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("product_view", "Product View"),
                            ("collection_view", "Collection View"),
                            ("add_to_cart", "Add to Cart"),
                            ("begin_checkout", "Begin Checkout"),
                            ("purchase", "Purchase"),
                            ("pixel_fire", "Pixel Fire"),
                            ("scroll", "Scroll"),
                            ("click", "Click"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("store_id", models.IntegerField(db_index=True)),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("product_id", models.IntegerField(blank=True, null=True)),
                ("collection_id", models.IntegerField(blank=True, null=True)),
                ("order_id", models.IntegerField(blank=True, null=True)),
                (
                    "utm_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("utm_term", models.CharField(blank=True, default="", max_length=255)),
                (
                    "utm_content",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("referrer", models.CharField(blank=True, default="", max_length=500)),
                (
                    "landing_page",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "customer_local_hour",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store_id", "event_type", "created_at"],
                        name="analytics_e_store_i_90e3d2_idx",
                    )
                ],
            },
        ),
    ]
