# Generated by Django 6.0.4 on 2026-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_event_schema_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page view"),
                    ("product_impression", "Product impression"),
                    ("product_click", "Product click"),
                    ("collection_impression", "Collection impression"),
                    ("collection_scroll_depth", "Collection scroll depth"),
                    ("add_to_cart", "Add to cart"),
                    ("checkout_start", "Checkout start"),
                    ("purchase", "Purchase"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="BeaconDlq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload_json", models.JSONField()),
                ("error_message", models.TextField()),
                ("attempt_count", models.PositiveSmallIntegerField(default=1)),
                ("last_attempted_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resolved", "created_at"],
                        name="analytics_b_resolve_08061d_idx",
                    )
                ],
            },
        ),
    ]
