"""
Product review system (TICKET-023).

Entities:
  Review        — a customer or AI-generated product review (store-scoped).
  ReviewRequest — tracks review-request emails scheduled after shipment (store-scoped).

Design notes:
- is_verified_buyer is set at submission time via check_verified_buyer(); never
  recomputed after creation. This prevents retroactive badge revocation when order
  history changes.
- reviewer_email is stored for the verified-buyer check and moderation; it is never
  rendered publicly.
- The verified-buyer check traverses OrderItem.product_variant__product because
  OrderItem stores a nullable FK to ProductVariant (snapshot rule, ADR-002).
  OrderItems whose variant was deleted (product_variant IS NULL) are excluded from
  the check — the buyer's purchase can no longer be linked, so the badge is not granted.
- ReviewRequest.scheduled_at = creation time + store.review_request_delay_days.
  The signal uses timezone.now() as the base because Order has no fulfilled_at field.
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from core.models import StoreOwnedModel, User


class ReviewStatus(models.TextChoices):
    PENDING = "pending", "Pending"
    APPROVED = "approved", "Approved"
    REJECTED = "rejected", "Rejected"
    SPAM = "spam", "Spam"


class ReviewProvenance(models.TextChoices):
    CUSTOMER = "customer", "Customer"
    AI_GENERATED = "ai_generated", "AI Generated"


class Review(StoreOwnedModel):
    """
    A product review — submitted by a customer or generated by an AI job.

    Invariants:
    - rating must be 1–5 (enforced by MinValue/MaxValueValidator and DB check).
    - is_verified_buyer is set once at submission time and never changed.
    - reviewer_email is internal-only; not exposed on public storefront views.
    - moderated_at / moderated_by are set by ReviewAdmin.save_model() when status changes.
    - For AI-generated reviews (provenance=AI_GENERATED), ai_job links the originating job.
    """

    product = models.ForeignKey(
        "catalog.Product",
        on_delete=models.CASCADE,
        related_name="reviews",
    )
    order = models.ForeignKey(
        "orders.Order",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="reviews",
        help_text="The order that generated this review (set for customer-submitted reviews).",
    )
    reviewer_name = models.CharField(max_length=100, blank=True)
    reviewer_email = models.CharField(
        max_length=254,
        blank=True,
        help_text="Internal only — never rendered publicly. Used for verified-buyer check.",
    )
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        help_text="Star rating from 1 (lowest) to 5 (highest).",
    )
    title = models.CharField(max_length=255, blank=True)
    body = models.TextField(blank=True)
    status = models.CharField(
        max_length=20,
        choices=ReviewStatus.choices,
        default=ReviewStatus.PENDING,
    )
    provenance = models.CharField(
        max_length=20,
        choices=ReviewProvenance.choices,
        default=ReviewProvenance.CUSTOMER,
    )
    is_verified_buyer = models.BooleanField(
        default=False,
        help_text=(
            "True when reviewer_email matches a paid order containing this product. "
            "Set once at submission time; never recomputed."
        ),
    )
    ai_job = models.ForeignKey(
        "aijobs.AiJob",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        help_text="The AI job that generated this review (AI_GENERATED provenance only).",
    )
    submitted_at = models.DateTimeField(auto_now_add=True)
    moderated_at = models.DateTimeField(null=True, blank=True)
    moderated_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        help_text="The admin user who last changed the review status.",
    )

    @classmethod
    def check_verified_buyer(cls, store, product, email: str) -> bool:
        """
        Return True when email has a paid order containing this product for this store.

        Traverses product_variant__product because OrderItem has no direct product FK
        (ADR-002 snapshot rule). OrderItems whose variant was deleted (NULL FK) are
        excluded — the product link is unrecoverable once the variant is deleted.
        """
        from orders.models import OrderItem

        # ADR-031 addendum audit (TICKET-051): .exists() used to silently
        # bypass StoreScopedManager's isolation raise — a real latent
        # unscoped read (only harmless because order__store=store was
        # already an explicit filter). Scoped via .for_store() now that
        # .exists() raises; order__store=store is redundant once for_store()
        # constrains OrderItem.store directly, so it is dropped.
        return OrderItem.objects.for_store(store).filter(
            order__payment_status="paid",
            order__customer_email__iexact=email,
            product_variant__product=product,
        ).exists()

    def __str__(self):
        return f"Review by {self.reviewer_name or f'Review #{self.pk}'} — {self.product} ({self.rating}★)"

    class Meta:
        verbose_name = "review"
        verbose_name_plural = "reviews"
        indexes = [
            models.Index(fields=["store", "product", "status"]),
            models.Index(fields=["store", "status", "submitted_at"]),
        ]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(rating__gte=1, rating__lte=5),
                name="review_rating_1_to_5",
            ),
        ]


class ReviewRequest(StoreOwnedModel):
    """
    A scheduled review-request email sent after order shipment.

    One row per order (enforced by the signal's get_or_create). The Celery task
    send_pending_review_requests() picks up rows where is_sent=False and
    scheduled_at <= now(), sends the email, then marks is_sent=True.

    Invariants:
    - scheduled_at = creation time + store.review_request_delay_days (set by signal).
    - is_sent / sent_at are updated atomically by the Celery task (update_fields).
    - has_change_permission returns False in admin — rows are read-only after creation.
    """

    order = models.ForeignKey(
        "orders.Order",
        on_delete=models.CASCADE,
        related_name="review_requests",
    )
    scheduled_at = models.DateTimeField(
        help_text="When to send the review-request email (order shipment time + delay_days).",
    )
    sent_at = models.DateTimeField(null=True, blank=True)
    is_sent = models.BooleanField(default=False)

    def __str__(self):
        return f"ReviewRequest for order {self.order_id} — sent={self.is_sent}"

    class Meta:
        verbose_name = "review request"
        verbose_name_plural = "review requests"
        indexes = [
            models.Index(fields=["is_sent", "scheduled_at"]),
        ]
