# Generated by Django 6.0.4 on 2026-07-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aijobs", "0004_alter_aijob_job_type"),
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(blank=True, max_length=512)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("generic", "Generic content page"),
                            ("contact", "Contact form page"),
                            ("quotation", "Quotation form page"),
                            ("policy", "Legal / policy page"),
                        ],
                        default="generic",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                ("show_in_header", models.BooleanField(default=False)),
                ("show_in_footer", models.BooleanField(default=False)),
                (
                    "nav_position",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Ascending display order within each nav zone (header/footer).",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "static page",
                "verbose_name_plural": "static pages",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("message", models.TextField()),
                ("lang_code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to="pages.staticpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
            },
        ),
        migrations.CreateModel(
            name="StaticPageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang_code",
                    models.CharField(
                        help_text="ISO 639-1 language code — e.g. 'fr', 'pt-br'.",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("manually_edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "slug_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Suggested slug from an AI slug_only job. Used as the initial slug for the auto-created Permalink; updated automatically when the signal fires.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_page_translations",
                        to="aijobs.aijob",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="pages.staticpage",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "static page translation",
                "verbose_name_plural": "static page translations",
            },
        ),
        migrations.AddIndex(
            model_name="staticpage",
            index=models.Index(
                fields=["store", "is_published"], name="pages_stati_store_i_554218_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staticpage",
            unique_together={("store", "slug")},
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["store", "status"], name="pages_conta_store_i_a99d07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["store", "created_at"], name="pages_conta_store_i_703628_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staticpagetranslation",
            unique_together={("store", "page", "lang_code")},
        ),
    ]
