set(SHORTCODES_FILES
    ${CMAKE_CURRENT_LIST_DIR}/AbstractShortCode.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractShortCode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractShortCodeLink.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractShortCodeLink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeVideo.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeVideo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeLinkFix.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeLinkFix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeLinkTr.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeLinkTr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeSpinnable.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeSpinnable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractShortCodeImage.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractShortCodeImage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeImageFix.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeImageFix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeImageTr.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeImageTr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeTitle.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeTitle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeBold.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeBold.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeItalic.h
    ${CMAKE_CURRENT_LIST_DIR}/ShortCodeItalic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeVideoDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeVideoDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeVideoDialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeImageDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeImageDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeImageDialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeLinkDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeLinkDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeLinkDialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeSpinnableDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeSpinnableDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeSpinnableDialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeTitleDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeTitleDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeTitleDialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeInlineDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeInlineDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/ShortCodeInlineDialog.ui
)
