# Generated by Django 6.0.4 on 2026-07-10 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
        ("stores", "0011_store_checkout_phone_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Server-minted opaque session identifier (secrets.token_urlsafe).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en",
                        help_text="ISO 639-1 lang_code the session was minted under (ADR-008).",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of accepted user messages this session (cap: 30).",
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "ended_reason",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("message_cap", "Message cap reached"),
                            ("token_cap", "Token budget reached"),
                            ("expired", "Expired"),
                            ("killed", "Killed (kill switch)"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "chat session",
                "verbose_name_plural": "chat sessions",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tool_trace_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {tool, input, output} dicts audited for this turn.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
            },
        ),
        migrations.CreateModel(
            name="StoreChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "subprocessor_terms_accepted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "model_id_override",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Blank = use the platform default (settings.CHAT_MODEL_ID).",
                        max_length=100,
                    ),
                ),
                (
                    "daily_message_budget",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Store-wide daily message cap (IP-independent), ADR-024 Decision 7.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_settings_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="StaticPage returned by get_store_policy(kind='contact'). When unset, falls back to the store's first published StaticPage of kind=CONTACT.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.staticpage",
                    ),
                ),
                (
                    "refund_policy_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="StaticPage returned by get_store_policy(kind='refund').",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.staticpage",
                    ),
                ),
                (
                    "shipping_policy_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="StaticPage returned by get_store_policy(kind='shipping').",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.staticpage",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "terms_policy_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="StaticPage returned by get_store_policy(kind='terms').",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pages.staticpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "store chat settings",
                "verbose_name_plural": "store chat settings",
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["store", "created_at"], name="chat_chatse_store_i_04d76b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["store", "ended_reason"], name="chat_chatse_store_i_b31595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["store", "session", "created_at"],
                name="chat_chatme_store_i_032af8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storechatsettings",
            constraint=models.UniqueConstraint(
                fields=("store",), name="unique_store_chat_settings"
            ),
        ),
    ]
