# Generated by Django 6.0.4 on 2026-07-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_collection_collectionproduct_and_more"),
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("coupon", "Coupon"),
                            ("gift_card_manual", "Gift card (manual)"),
                            ("gift_card_auto", "Gift card (auto-issued)"),
                        ],
                        default="coupon",
                        max_length=20,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed amount"),
                            ("free_product", "Free product"),
                            ("free_shipping", "Free shipping"),
                        ],
                        default="percentage",
                        help_text="Ignored for gift card types.",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percent (0–100) for percentage type; fixed amount for fixed_amount type.",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="None means unlimited.", null=True
                    ),
                ),
                (
                    "usage_limit_per_customer",
                    models.PositiveIntegerField(
                        default=1, help_text="Per customer account usage limit."
                    ),
                ),
                (
                    "per_email_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Per-email limit for guest checkout (ADR-002 §4).",
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Atomically incremented on redemption via F() expression + select_for_update.",
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Gift card face value. Only meaningful for gift_card_manual / gift_card_auto.",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific collections. Empty = applies to all.",
                        related_name="discount_codes",
                        to="catalog.collection",
                    ),
                ),
                (
                    "product_conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific products. Empty = applies to all.",
                        related_name="discount_codes",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "verbose_name": "discount code",
                "verbose_name_plural": "discount codes",
            },
        ),
        migrations.CreateModel(
            name="DiscountCodeEmailUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "discount_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_uses",
                        to="discounts.discountcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "discount code email use",
                "verbose_name_plural": "discount code email uses",
            },
        ),
        migrations.CreateModel(
            name="GiftCardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive = spend; negative = refund reversal.",
                        max_digits=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gift_card",
                    models.ForeignKey(
                        help_text="Must be a gift_card_manual or gift_card_auto DiscountCode.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="discounts.discountcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "gift card transaction",
                "verbose_name_plural": "gift card transactions",
            },
        ),
    ]
