# Generated by Django 6.0.4 on 2026-07-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("stores", "0003_alter_field_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardtransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gift_card_transactions",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stores.store"
            ),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["store", "code"], name="discounts_d_store_i_aafe36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["store", "is_active", "ends_at"],
                name="discounts_d_store_i_a1e100_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="discountcode",
            unique_together={("store", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="discountcodeemailuse",
            unique_together={("discount_code", "email")},
        ),
        migrations.AddIndex(
            model_name="giftcardtransaction",
            index=models.Index(
                fields=["store", "gift_card"], name="discounts_g_store_i_a0f52e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcardtransaction",
            index=models.Index(
                fields=["store", "created_at"], name="discounts_g_store_i_b2d146_idx"
            ),
        ),
    ]
