# Generated by Django 6.0.4 on 2026-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0003_discount_model_gaps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="times_used",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Atomically incremented on redemption via a single conditional UPDATE (ADR-002 §4). Never increment Python-side or with an unconditional UPDATE.",
            ),
        ),
    ]
