# Generated by Django 6.0.4 on 2026-07-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_productpageversion_productpageversionimage"),
        ("discounts", "0004_alter_discountcode_times_used"),
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="refund_flagged",
            field=models.BooleanField(
                default=False,
                help_text="ADR-029 D9: set when this campaign-issued gift card had already been partially/fully spent when its triggering order was refunded. The balance is never clawed back automatically — manual review only.",
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="refund_flagged_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Audit note explaining why refund_flagged was set.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="GiftCardCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "owner_scope",
                    models.CharField(
                        choices=[
                            ("store", "Store admin"),
                            ("platform", "Platform (super-admin)"),
                        ],
                        default="platform",
                        help_text="Scope of the campaign creator. The v1 UI (super-admin) only creates 'platform' rows; kept open for a future store-admin variant (D1).",
                        max_length=10,
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("order_paid", "Order paid"),
                            ("nth_order", "Nth order (reserved)"),
                            ("spend_threshold", "Spend threshold (reserved)"),
                            ("win_back", "Win-back (reserved)"),
                        ],
                        default="order_paid",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_scope",
                    models.CharField(
                        choices=[
                            ("all_products", "All products"),
                            ("manual_products", "Manually add products"),
                            ("conditions", "Products based on conditions"),
                        ],
                        default="all_products",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_rules_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reserved for trigger_scope='conditions' (hidden in v1 UI — D2). Phase 1 never evaluates this field.",
                    ),
                ),
                (
                    "value_mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Set value"),
                            (
                                "percent_of_order",
                                "Percentage of order total (pending decision)",
                            ),
                            (
                                "percent_discount_coupon",
                                "Set % discount off order (pending decision)",
                            ),
                        ],
                        default="fixed",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed face value of the issued gift card, in the store currency.",
                        max_digits=10,
                    ),
                ),
                (
                    "expiry_mode",
                    models.CharField(
                        choices=[
                            ("relative_days", "Set number of days"),
                            ("absolute_date", "Specific date"),
                        ],
                        default="relative_days",
                        max_length=20,
                    ),
                ),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Used when expiry_mode='relative_days'. Default matches the legacy platform's admin-020 behavior.",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Used when expiry_mode='absolute_date'.",
                        null=True,
                    ),
                ),
                ("cap_enabled", models.BooleanField(default=False)),
                (
                    "cap_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Max gift cards issued to the same recipient email within the window (D5).",
                    ),
                ),
                ("cap_window_value", models.PositiveIntegerField(default=30)),
                (
                    "cap_window_unit",
                    models.CharField(
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                (
                    "max_issued_cards",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Budget cap across all recipients. Null = unlimited (D9).",
                        null=True,
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Blank = use the platform 'gift_card_campaign' template (D7).",
                        max_length=255,
                    ),
                ),
                (
                    "email_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Blank = use the platform 'gift_card_campaign' template (D7). Supports the '[DISCOUNT]' and '[GENERATED GIFT CARD CODE]' token pills.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
                (
                    "trigger_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Used only when trigger_scope='manual_products'.",
                        related_name="gift_card_campaigns",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "gift card campaign",
                "verbose_name_plural": "gift card campaigns",
            },
        ),
        migrations.AddField(
            model_name="discountcode",
            name="gift_card_campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for gift_card_auto codes issued by an automated gift-card campaign (ADR-029 D1). Never set for merchant/lead_capture/sold codes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_codes",
                to="discounts.giftcardcampaign",
            ),
        ),
        migrations.AddIndex(
            model_name="giftcardcampaign",
            index=models.Index(
                fields=["store", "status"], name="disc_gcc_store_status_idx"
            ),
        ),
    ]
