# Generated by Developer Agent — TICKET-002
# Adds: Organization, Theme, full Store model, StoreEmployee.
# Replaces the minimal Store stub from 0001_initial with the full schema.
#
# Non-nullable fields added to the existing Store table (subdomain, primary_language,
# timezone, default_currency) use a safe one-off default so existing dev/test rows
# are not orphaned.  Production Store rows should not exist at this point — this is
# a foundation migration.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ------------------------------------------------------------------ #
        # 1. Organization (no FK dependencies)                               #
        # ------------------------------------------------------------------ #
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=["is_default"],
                name="unique_default_organization",
            ),
        ),
        # ------------------------------------------------------------------ #
        # 2. Theme stub (no FK dependencies)                                 #
        # ------------------------------------------------------------------ #
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "theme",
                "verbose_name_plural": "themes",
            },
        ),
        # ------------------------------------------------------------------ #
        # 3. Expand Store with the full field set                            #
        # ------------------------------------------------------------------ #
        # New non-nullable fields use preserve_default=False so the default
        # only applies during this migration and is not baked into the model.
        migrations.AddField(
            model_name="store",
            name="subdomain",
            field=models.SlugField(
                default="placeholder",
                max_length=255,
                unique=True,
                help_text="Always lower-case ASCII. Populated via core.slugs.make_slug.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="custom_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="store",
            name="primary_language",
            field=models.CharField(
                default="en",
                max_length=10,
                help_text="ISO 639-1 language code.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="store",
            name="default_currency",
            field=models.CharField(
                default="USD",
                max_length=3,
                help_text="ISO 4217 currency code.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="stores.theme",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional grouping under an Organization for payment routing filters. "
                    "Carries no config inheritance — orders can still route to any eligible Org."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="stores.organization",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="store",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Set by soft_delete(); null means not deleted.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"verbose_name": "store", "verbose_name_plural": "stores"},
        ),
        # ------------------------------------------------------------------ #
        # 4. StoreEmployee (depends on Store and AUTH_USER_MODEL)            #
        # ------------------------------------------------------------------ #
        migrations.CreateModel(
            name="StoreEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_access", models.BooleanField(default=False)),
                ("permissions_json", models.JSONField(default=dict)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "store employee",
                "verbose_name_plural": "store employees",
            },
        ),
        migrations.AddConstraint(
            model_name="storeemployee",
            constraint=models.UniqueConstraint(
                fields=["user", "store"],
                name="unique_store_employee",
            ),
        ),
    ]
