# Generated by Django 6.0.4 on 2026-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_organization_theme_store_full_storeemployee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Exactly one Organization may be the platform default. Enforced by a partial unique index.",
            ),
        ),
        migrations.AlterField(
            model_name="storeemployee",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the user accepts the store invitation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storeemployee",
            name="full_access",
            field=models.BooleanField(
                default=False,
                help_text="Master override: bypasses all permissions_json module checks.",
            ),
        ),
        migrations.AlterField(
            model_name="storeemployee",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Updated on each /admin/ login for this store.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storeemployee",
            name="permissions_json",
            field=models.JSONField(
                default=dict,
                help_text='18-module permission matrix. Keys are module names; values are "full", "limited", or "none". Ignored when full_access is True.',
            ),
        ),
    ]
