# Generated by Django 6.0.4 on 2026-07-04 08:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_store_password_protection"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Lowercase hostname, no scheme/port — e.g. 'mystore.fr', 'shop.mystore.com'. (ADR-008: deprecated, use StoreDomain/StoreLanguage for new code.)",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="The store's canonical domain. Exactly one per store.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "store domain",
                "verbose_name_plural": "store domains",
            },
        ),
        migrations.CreateModel(
            name="StoreLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang_code",
                    models.CharField(
                        help_text="ISO 639-1 code — doubles as the URL path prefix when use_path_prefix=True.",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z]{2}(-[a-z]{2})?$",
                                "Lowercase ISO 639-1 code, optionally with a region suffix — e.g. 'en', 'pt-br'.",
                            )
                        ],
                    ),
                ),
                (
                    "use_path_prefix",
                    models.BooleanField(
                        help_text="False = served at the domain root (this is the domain's default language, ML-002). True = served under /<lang_code>/ on the domain."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The store's default language (hreflang x-default). Exactly one per store.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled languages serve 410 Gone (ML-012); rows are never deleted.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        help_text="The domain this language edition is served from.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="languages",
                        to="stores.storedomain",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "store language",
                "verbose_name_plural": "store languages",
            },
        ),
        migrations.CreateModel(
            name="ShippingCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 — e.g. 'US', 'FR'.",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "ISO 3166-1 alpha-2, uppercase."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_countries",
                        to="stores.storelanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping country",
                "verbose_name_plural": "shipping countries",
            },
        ),
        migrations.AddConstraint(
            model_name="storedomain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("store",),
                name="unique_primary_domain_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="storelanguage",
            constraint=models.UniqueConstraint(
                fields=("store", "lang_code"), name="unique_lang_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="storelanguage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("use_path_prefix", False)),
                fields=("domain",),
                name="one_root_language_per_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="storelanguage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("store",),
                name="one_default_language_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingcountry",
            constraint=models.UniqueConstraint(
                fields=("store_language", "country_code"),
                name="unique_country_per_store_language",
            ),
        ),
    ]
