# Generated by Django 6.0.4 on 2026-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_storedomain_storelanguage_shippingcountry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="review_request_delay_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Days after shipment before sending a review-request email.",
            ),
        ),
    ]
