# Generated by Django 6.0.4 on 2026-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0008_populate_store_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Deprecated: use StoreDomain/StoreLanguage instead. Will be removed after migration is complete.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="primary_language",
            field=models.CharField(
                default="en",
                help_text="ISO 639-1 language code. Deprecated: use StoreDomain/StoreLanguage instead. Will be removed after migration is complete.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="subdomain",
            field=models.SlugField(
                help_text="Always lower-case ASCII. Populated via core.slugs.make_slug. Deprecated: use StoreDomain/StoreLanguage instead. Will be removed after migration is complete.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="storedomain",
            name="host",
            field=models.CharField(
                help_text="Fully qualified hostname served by this store (e.g. shop.example.com).",
                max_length=253,
                unique=True,
            ),
        ),
    ]
