# Generated by Django 6.0.4 on 2026-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0010_theme_engine_extend_store_theme_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="checkout_phone_mode",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("optional", "Optional"),
                    ("required", "Required"),
                ],
                default="optional",
                help_text="Controls the phone field at checkout (CO-003). hidden = not shown; optional = shown but not required (default); required = shown and must be filled.",
                max_length=10,
            ),
        ),
    ]
