# Generated by Django 6.0.4 on 2026-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="coverage_areas_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Informational area tokens (EU, ROW, country codes) for the super-admin UI. Routing reads rule conditions_json, not this field.",
            ),
        ),
    ]
