# Generated by Django 6.0.4 on 2026-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0013_merge_collections_into_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeemployee",
            name="invited_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="storeemployee",
            name="invited_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="storeemployee",
            name="permissions_json",
            field=models.JSONField(
                default=dict,
                help_text='19-module permission matrix (stores.modules.MODULES). Keys are module names; values are "full", "limited", or "none" (only Orders allows "limited" — ADR-033 D1a). Ignored when full_access is True.',
            ),
        ),
    ]
