# Generated by Django 6.0.4 on 2026-07-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0011_store_checkout_phone_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyConverterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_refresh_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="ECB daily-feed auto-refresh. Off by default (ADR-023 §1).",
                    ),
                ),
                (
                    "rounding_mode",
                    models.CharField(
                        choices=[
                            ("none", "No rounding adjustment"),
                            ("psychological_99", 'Psychological ("...99") rounding'),
                        ],
                        default="psychological_99",
                        max_length=20,
                    ),
                ),
                (
                    "stale_hours",
                    models.PositiveIntegerField(
                        default=48,
                        help_text="Only meaningful for auto-fetched (source='api:ecb') rates.",
                    ),
                ),
            ],
            options={
                "verbose_name": "currency converter settings",
                "verbose_name_plural": "currency converter settings",
            },
        ),
        migrations.CreateModel(
            name="CurrencyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code, e.g. 'USD', 'JPY'.",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(blank=True, default="", max_length=8)),
                (
                    "symbol_placement",
                    models.CharField(
                        choices=[
                            ("prefix", "Prefix (e.g. $45.99)"),
                            ("suffix", "Suffix (e.g. 45.99 kr)"),
                        ],
                        default="prefix",
                        max_length=8,
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="ISO 4217 minor-unit count. 2 for most currencies, 0 for JPY/KRW-style currencies (ADR-023 §2/§6, DECIDED 2026-07-10 — 0-decimal currencies round to whole units using the same psychological rule).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_to_reference",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Rate vs the EUR anchor. EUR's own row is always 1.00000000.",
                        max_digits=18,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual entry"),
                            ("api:ecb", "ECB daily reference-rate feed"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="The rate this row held immediately before the last successful write.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "last_refresh_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "currency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate",
                        to="currency.currencydefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "currency rate",
                "verbose_name_plural": "currency rates",
                "ordering": ["currency__code"],
            },
        ),
        migrations.CreateModel(
            name="StoreCurrencySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_settings",
                        to="currency.currencydefinition",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stores.store"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store", "currency"],
                        name="currency_st_store_i_16799c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "currency"), name="unique_store_currency"
                    )
                ],
            },
        ),
    ]
