# Generated by Django 6.0.4 on 2026-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_seed_ecb_currencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencydefinition",
            name="code_placement",
            field=models.CharField(
                choices=[
                    ("prefix", "Prefix (e.g. $45.99)"),
                    ("suffix", "Suffix (e.g. 45.99 kr)"),
                ],
                default="suffix",
                help_text="Where the ISO code renders relative to the symbol+amount, when show_code is on.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="currencydefinition",
            name="show_code",
            field=models.BooleanField(
                default=False,
                help_text="Show the ISO code alongside the symbol, e.g. '45.99 $ CAD' (ADR-023 §2 addendum, human decision 2026-07-11 — restores the admin-011 screenshot's 'Code visibility' control).",
            ),
        ),
    ]
